### ISSUE TITLE
Seria interessanter colocar uma nota ou fazer outro vídeo com alguns passos anteriores a primeira aula

### ISSUE THREAD

**Issue by tgmarinho** [Rocketseat/course-adonis-acl#1]
Olá @HigoRibeiro tudo bem?

Seria interessanter colocar uma nota ou fazer outro vídeo com alguns passos anteriores a primeira aula. Para renomar o .env.example e deixar o banco de dados rodando para depois rodar adonis run:migrations. 

Isso é bastante óbvio talvez para quem já esta trabalhando algum tempo com adonis (stack) porém para quem nunca fez (está aprendendo) não fica tão óbvio assim.

Valeu, Obrigado!

**Comment by HigoRibeiro** [comment]
Boa @tgmarinho !!
